version: "3"

networks:
  traefik:
    name: "${TRAEFIK_NETWORK_NAME}"
    external: true

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - default
      - traefik
    environment:
      - TZ=Asia/Taipei
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK_NAME}
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_DOMAIN}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt_cf
      - traefik.http.routers.whoami.tls.domains[0].main=${CERT_DOMAIN}
      - traefik.http.services.whoami_web.loadbalancer.server.port=80
